#!/bin/bash 
sleep 10

#set -x	
killall motion
killall gatestatus.py
find /opt/data/motion* -empty -type f -exec rm -f {} \;
rm -r -f /var/log/motion/*.log

mkdir -p /var/run/motion

cd /home/iotuser
fuser /dev/video0 || motion

while true; do
	dt=`date +%Y%m%d%H%M%S`
  date >> /var/log/motion/start_gatekeeper.log
  nohup /home/iotuser/gate/src/gatestatus.py -daemon >> /var/log/motion/start_gatekeeper.log
done &

